### ISSUE TITLE
Build fails with coq 8.12

### ISSUE THREAD

**Issue by h0nzZik** [amintimany/Categories#1]
With coq 8.12, the build fails with the following output:
```
File "./Functor/Functor.v", line 89, characters 15-20:
Error:
In environment
C : Category
C' : Category
F, G : (C --> C')%functor
Oeq : F _o = G _o
The term "G _a" has type "?a --> ?b → (G _o) ?a --> (G _o) ?b"
while it is expected to have type
 "∀ x x0 : C, x --> x0 → (G _o) x --> (G _o) x0".

make[1]: *** [Makefile:716: Functor/Functor.vo] Error 1
make: *** [Makefile:339: all] Error 2
```

**Comment by amintimany** [comment]
Thanks for opening the issue. I just noticed it now; sorry. However, this issue has been closed by 19e00bb4d6027baaa39475b882a362c2cc107185. I just realized now that the latest version of master does not compile with 8.13.1. I will fix this very soon hopefully.
